### ISSUE TITLE
[GUIDE] How to use with microsoft account?

### ISSUE THREAD

**Issue by pooxie-proxy** [zardoy/prismarine-web-client#223]
Ive seen that there is code for this but how is it done via the client

**Comment by zardoy** [comment]
@pooxie-proxy
1. Connect to server requiring auth (working in online mode only)
2. Login to MS account on their portal, use the code provided by us to authorise access
3. Continue connecting to a vanilla server

please connect to only trusted servers otherwise you might get banned by anti cheat plugins since this client is not official

Supported Versions: 1.19.4 - 1.20.6

**Comment by pooxie-proxy** [comment]
> @pooxie-proxy
> 
> 1. Connect to server requiring auth (working in online mode only)
> 2. Login to MS account on their portal, use the code provided by us to authorise access
> 3. Continue connecting to a vanilla server
> 
> please connect to only trusted servers otherwise you might get banned by anti cheat plugins since this client is not official

thanks!

**Comment by zardoy** [comment]
might be broken for some accounts, will be fixed in ~ 4 days
update: if its broken for your account please give feedback
